site_name: RELAI

use_directory_urls: false

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode (Mantine-inspired colors)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode (Mantine dark theme colors)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate
    - toc.follow
    - content.code.copy
    - content.code.select
  # font:
  #   text: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif
  #   code: SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace
  logo: false
  favicon: false
  # custom_dir: docs_overrides

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_toc_entry: true
            show_source: false
            merge_init_into_class: true
            docstring_style: google
            heading_level: 1

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: false
      linenums: false
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables

repo_url: https://github.com/relai-ai/relai-sdk
repo_name: relai-ai/relai-sdk

extra:
  generator: false

nav:
  - Home: index.md
  - Tutorials:
      - tutorials/index.md
      - Persona Set: tutorials/persona-set.md
      - Mock MCP Server: tutorials/mock-mcp-server.md
      - Custom Evaluator: tutorials/custom-evaluator.md
  - API Reference:
      - api/index.md
      - Types: api/types.md
      - Benchmark: api/benchmark.md
      - Mockers: api/mockers.md
      - Simulator: api/simulator.md
      - Evaluator: api/evaluator.md
      - Critico: api/critico.md
      - Maestro: api/maestro.md

docs_dir: docs
